.. index:: 
  !TrackedFaceList.clear Method
  
.. _tracked_face_list_clear_class_method:

===============================================================================
TrackedFaceList.clear Method
===============================================================================

Module: :ref:`TrackedFaceList<tracked_face_list_class>`

Definition
----------

Clears the TrackedFaceList object.


.. tab-set::

    .. tab-item:: C
      :sync: C

      .. code:: C

        int id3TrackedFaceList_Clear (
            ID3_TRACKED_FACE_LIST hTrackedFaceList)

      **Parameters**

        .. line-block::

          ``hTrackedFaceList`` :ref:`ID3_TRACKED_FACE_LIST<tracked_face_list_class>`
          :guilabel:`in` Handle to the TrackedFaceList object.


      **Returns**

        .. line-block::

          ``int``
          An error code.
          See :ref:`id3FaceError<face_error_enum>` file for the list of possible error codes.

    .. tab-item:: Dart
      :sync: Dart

      .. code:: Dart

        void clear()

      **Exceptions**

        .. line-block::

          :ref:`FaceException<face_exception>`
          An error has occurred during Face Library execution.


    .. tab-item:: C#
      :sync: C#

      .. code:: C#

        public void Clear()

      **Exceptions**

        .. line-block::

          :ref:`FaceException<face_exception>`
          An error has occurred during Face Library execution.


    .. tab-item:: Java
      :sync: Java

      .. code:: Java

        public void clear() throws FaceException

      **Exceptions**

        .. line-block::

          :ref:`FaceException<face_exception>`
          An error has occurred during Face Library execution.


    .. tab-item:: Python
      :sync: Python

      .. code:: Python

        clear(self) -> None

      **Exceptions**

        .. line-block::

          :ref:`FaceException<face_exception>`
          An error has occurred during Face Library execution.


    .. tab-item:: Swift
      :sync: Swift

      .. code:: Swift

        public func clear() throws

      **Exceptions**

        .. line-block::

          :ref:`FaceException<face_exception>`
          An error has occurred during Face Library execution.



