.. index:: 
  !PointList.clear Method
  
.. _point_list_clear_class_method:

===============================================================================
PointList.clear Method
===============================================================================

Module: :ref:`PointList<point_list_class>`

Definition
----------

Clears the PointList object.


.. tab-set::

    .. tab-item:: C
      :sync: C

      .. code:: C

        int id3FacePointList_Clear (
            ID3_FACE_POINT_LIST hPointList)

      **Parameters**

        .. line-block::

          ``hPointList`` :ref:`ID3_FACE_POINT_LIST<point_list_class>`
          :guilabel:`in` Handle to the PointList object.


      **Returns**

        .. line-block::

          ``int``
          An error code.
          See :ref:`id3FaceError<face_error_enum>` file for the list of possible error codes.

    .. tab-item:: Dart
      :sync: Dart

      .. code:: Dart

        void clear()

      **Exceptions**

        .. line-block::

          :ref:`FaceException<face_exception>`
          An error has occurred during Face Library execution.


    .. tab-item:: C#
      :sync: C#

      .. code:: C#

        public void Clear()

      **Exceptions**

        .. line-block::

          :ref:`FaceException<face_exception>`
          An error has occurred during Face Library execution.


    .. tab-item:: Java
      :sync: Java

      .. code:: Java

        public void clear() throws FaceException

      **Exceptions**

        .. line-block::

          :ref:`FaceException<face_exception>`
          An error has occurred during Face Library execution.


    .. tab-item:: Python
      :sync: Python

      .. code:: Python

        clear(self) -> None

      **Exceptions**

        .. line-block::

          :ref:`FaceException<face_exception>`
          An error has occurred during Face Library execution.


    .. tab-item:: Swift
      :sync: Swift

      .. code:: Swift

        public func clear() throws

      **Exceptions**

        .. line-block::

          :ref:`FaceException<face_exception>`
          An error has occurred during Face Library execution.



