.. index:: 
  !FaceTemplateDict.clear Method
  
.. _face_template_dict_clear_class_method:

===============================================================================
FaceTemplateDict.clear Method
===============================================================================

Module: :ref:`FaceTemplateDict<face_template_dict_class>`

Definition
----------

Clears the FaceTemplateDict object.


.. tab-set::

    .. tab-item:: C
      :sync: C

      .. code:: C

        int id3FaceTemplateDict_Clear (
            ID3_FACE_TEMPLATE_DICT hFaceTemplateDict)

      **Parameters**

        .. line-block::

          ``hFaceTemplateDict`` :ref:`ID3_FACE_TEMPLATE_DICT<face_template_dict_class>`
          :guilabel:`in` Handle to the FaceTemplateDict object.


      **Returns**

        .. line-block::

          ``int``
          An error code.
          See :ref:`id3FaceError<face_error_enum>` file for the list of possible error codes.

    .. tab-item:: Dart
      :sync: Dart

      .. code:: Dart

        void clear()

      **Exceptions**

        .. line-block::

          :ref:`FaceException<face_exception>`
          An error has occurred during Face Library execution.


    .. tab-item:: C#
      :sync: C#

      .. code:: C#

        public void Clear()

      **Exceptions**

        .. line-block::

          :ref:`FaceException<face_exception>`
          An error has occurred during Face Library execution.


    .. tab-item:: Java
      :sync: Java

      .. code:: Java

        public void clear() throws FaceException

      **Exceptions**

        .. line-block::

          :ref:`FaceException<face_exception>`
          An error has occurred during Face Library execution.


    .. tab-item:: Python
      :sync: Python

      .. code:: Python

        clear(self) -> None

      **Exceptions**

        .. line-block::

          :ref:`FaceException<face_exception>`
          An error has occurred during Face Library execution.


    .. tab-item:: Swift
      :sync: Swift

      .. code:: Swift

        public func clear() throws

      **Exceptions**

        .. line-block::

          :ref:`FaceException<face_exception>`
          An error has occurred during Face Library execution.



